"""对象—叙述—依据的基础记忆编译。"""

from cold_start.compilation.leaf import (
    LeafBasicCompiler,
    create_leaf_artifact_paths,
    load_exploration_inputs,
    write_leaf_artifact,
)
from cold_start.compilation.models import (
    Assertion,
    Evidence,
    FullCompilationSnapshot,
    MemoryObject,
    MemoryPackage,
    MissingObjectCandidate,
    MissingObjectDiscoveryOutput,
    MissingObjectRecoveryArtifact,
    MissingObjectReviewOutput,
    NodeIntegrationResult,
    ParentIntegrationDecision,
    RegionCompilationArtifact,
    TemporalScope,
    object_assertion_ids,
    object_evidence_ids,
    object_reference_ids,
    package_warnings,
    render_statement,
    rewrite_object_references,
)
from cold_start.compilation.operations import (
    apply_missing_object_reviews,
    apply_parent_decision,
    rebase_package,
    union_packages,
)
from cold_start.compilation.tree import (
    FullBasicCompilationRunner,
    create_full_artifact_paths,
    open_full_artifact_paths,
    write_full_artifacts,
)

__all__ = [
    "Assertion",
    "Evidence",
    "FullBasicCompilationRunner",
    "FullCompilationSnapshot",
    "LeafBasicCompiler",
    "MemoryObject",
    "MemoryPackage",
    "MissingObjectCandidate",
    "MissingObjectDiscoveryOutput",
    "MissingObjectRecoveryArtifact",
    "MissingObjectReviewOutput",
    "NodeIntegrationResult",
    "ParentIntegrationDecision",
    "RegionCompilationArtifact",
    "TemporalScope",
    "apply_missing_object_reviews",
    "apply_parent_decision",
    "create_full_artifact_paths",
    "create_leaf_artifact_paths",
    "load_exploration_inputs",
    "object_assertion_ids",
    "object_evidence_ids",
    "object_reference_ids",
    "open_full_artifact_paths",
    "package_warnings",
    "rebase_package",
    "render_statement",
    "rewrite_object_references",
    "union_packages",
    "write_full_artifacts",
    "write_leaf_artifact",
]
